name: Release CI
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install deps
        run: pnpm install

      - name: Test
        run: pnpm run ci

      - name: Release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Mod
        run: pnpm run upload
        env:
          FACTORIO_TOKEN: ${{ secrets.FACTORIO_TOKEN }}
